# Generated by Django 3.0.3 on 2022-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('image', models.FileField(upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
