# Generated by Django 3.0.3 on 2022-03-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gene',
            name='ec',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='geneattributelink',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='geneattributelink',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='organisation',
        ),
        migrations.AddField(
            model_name='appuser',
            name='birthDate',
            field=models.DateTimeField(blank=True, default='1990-01-01 00:00:00+01'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=354, on_delete=django.db.models.deletion.CASCADE, to='socialmedia.AppUser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='EC',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='GeneAttributeLink',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sequencing',
        ),
        migrations.AddField(
            model_name='useruserfriend',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend_user1', to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='useruserfriend',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend_user2', to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='useruserchat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chat_user1', to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='useruserchat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chat_user2', to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='_appuser_chats_+', through='socialmedia.UserUserChat', to='socialmedia.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_appuser_friends_+', through='socialmedia.UserUserFriend', to='socialmedia.AppUser'),
        ),
    ]
