# Generated by Django 3.0.3 on 2022-03-06 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_auto_20220306_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthDate',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1)),
        ),
    ]
