# Generated by Django 3.0.3 on 2022-03-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_auto_20220306_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='friends',
        ),
    ]
