# Generated by Django 3.0.3 on 2022-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_remove_appuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_appuser_friends_+', through='socialmedia.UserUserFriend', to='socialmedia.AppUser'),
        ),
    ]
