# Generated by Django 3.0.3 on 2022-03-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0012_appuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruserchat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useruserchat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='useruserchat',
            name='user2',
        ),
        migrations.AddField(
            model_name='useruserchat',
            name='friends',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socialmedia.UserUserFriend'),
            preserve_default=False,
        ),
    ]
