# Generated by Django 3.0.3 on 2022-03-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0014_auto_20220310_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socialmedia.AppUser'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='socialmedia.AppUser'),
        ),
        migrations.AlterField(
            model_name='useruserfriend',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user1', to='socialmedia.AppUser'),
        ),
        migrations.AlterField(
            model_name='useruserfriend',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user2', to='socialmedia.AppUser'),
        ),
    ]
